name: lhm
up:
  - homebrew:
      - mysql-client@5.7:
          or: [mysql@5.7]
          conflicts: [shopify/shopify/mysql-client, mysql-connector-c, mysql, mysql-client]
      - wget
  - ruby: 2.7.0
  - bundler
  - docker
<<<<<<< HEAD
  - custom:
      name: Docker Compose
      met?: docker compose ls | grep -ioE -q "lhm.*running\(3\)"
      meet: docker compose up -d
  - custom:
      name: Waiting for DBs to be operational
      met?: ./scripts/helpers/wait-for-dbs.sh
      meet: ":"
=======
#  - custom:
#      name: Database
#      met?: test -f spec/integration/database.yml && test "$(./dbdeployer/sandboxes/rsandbox_5_7_22/status_all | grep on\  | wc -l | xargs echo)" = "2"
#      meet: ./dbdeployer/install.sh
#      down: ./dbdeployer/sandboxes/rsandbox_5_7_22/stop_all
  - custom:
      name: Docker Compose
      met?: docker-compose ls | grep -ioE -q "lhm.*running\(4\)"
      meet: docker-compose up -d
>>>>>>> 2d5f862 (Test & dev environment now running with docker-compose)

commands:
  unit: bundle exec rake unit
  int: bundle exec rake integration
  test: bundle exec rake unit && bundle exec rake integration
  cov: rm -rf coverage; COV=1 bundle exec rake unit && bundle exec rake integration; open coverage/index.html
  logs:
    desc: "See the DB logs (ctrl-c + ctrl-c to exit)"
    run: docker-compose logs -f
  clean:
    run: docker-compose rm -v -s -f && docker-compose up -d
