master:
  host: mysql-1
  user: root
  password: password
  port: 33006
slave:
  host: mysql-2
  user: root
  password: password
  port: 33007
proxysql:
  host: proxysql
  user: root
  password: password
  port: 33005
master_toxic:
  host: toxiproxy
  user: root
  password: password
  port: 22220
proxysql_toxic:
  host: toxiproxy
  user: root
  password: password
  port: 22222
