name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true
      - name: Install Ruby packages
        run: bundle install
      - name: Install Ubuntu packages
        run: sudo apt-get update && sudo apt-get install numactl libaio-dev libmysqlclient-dev
      - name: Setup MySQL and ProxySQL (docker-compose)
        run: docker-compose up -d # Might have to change to docker compose up -d (i.e. Compose V2) when the Ubuntu image changes the docker-compose version
      - name: Wait until DBs are alive
        run: ./scripts/helpers/wait-for-dbs.sh
        timeout-minutes: 2
      - name: Run tests
        run: bundle exec rake specs